name: Mixed inputs

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Who to greet
        options: 
        - monalisa
        - lisamona
      message:
        required: true
      use-emoji:
        type: boolean
        description: Include 🎉🤣 emojis

jobs:
  prepare-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: |
          if ${{ github.event.inputs.name == 'monalisa' }}; then MATRIX={\"include\":[{\"username\":\"monalisa\"},{\"username\":\"lisamona\"}]}; else MATRIX={\"include\":[{\"username\":\"lisamona\"}]}; fi
          echo "${MATRIX}"
          echo "::set-output name=matrix::${MATRIX}"
  greet:
    needs: prepare-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJSON(needs.prepare-matrix.outputs.matrix)}}
    steps:
    - name: Send greeting to ${{ matrix.username }}
      run: echo "${{ github.event.inputs.message }} ${{ fromJSON('["", "🥳"]')[github.event.inputs.use-emoji == 'true'] }} ${{ github.event.inputs.name }}"
